language: php
php: 
  - 7.3
  - 7.4
os: linux

before_script:
  - rm -rf composer.lock
  - composer install
  - cp .env.example .env
  - php artisan key:generate

script:
  - mkdir -p build/logs
  - ./vendor/bin/pest --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io.bash)